### ISSUE TITLE
Cannot start BitCannon

### ISSUE THREAD

**Issue by duramato** [bitcannon-org/bitcannon-web#17]
I get this error when trying to start up bitcannon after updating to the latest version 
```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at Object.<anonymous> (/root/bitcannon/index.js:31:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by OmgImAlexis** [comment]
You need the `config.json` file from the development branch.
